overview:
  title: Point Of Interest (POI)
  image: logo.png
  description: Shows how a product detail page with 360° images and points of interest used looks.
  facts:
    - JS built 360° Zoom Viewer
    - Points Of Interest
    - Thumbnail Labels
  order: 3
schema: bootstrap-taupe
sample:
  menu:
    data:misc-menu.yml
  highlight: HIGHLIGHT OF THE DAY
  footer:
    credits:
      photos:
        - author: 360ties GmbH
      viewer:
        link: https://www.neptunelabs.com/fsi-viewer/
  fsi:
    viewer: true
    touchZoom: true
    thumbBar: true
  bootstrap:
    icons: true
